'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class loansub
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''headDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents headDescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtAccountNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNo As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''dtReqDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtReqDate As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''ddlTypeLoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTypeLoan As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBranch As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''selStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selStatus As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''gbLoanRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbLoanRef As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtLoanRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLoanRefNo As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtLoanRefNo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLoanRefNo2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtPersonId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPersonId As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtPersonName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPersonName As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''linkPerson1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkPerson1 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''linkEditPerson1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkEditPerson1 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''gbPerson1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbPerson1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtPersonId2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPersonId2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtPersonName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPersonName2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''linkPerson2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkPerson2 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''linkEditPerson2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkEditPerson2 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''gbPerson2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbPerson2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtPersonId3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPersonId3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtPersonName3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPersonName3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''linkPerson3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkPerson3 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''linkEditPerson3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkEditPerson3 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''gbPerson3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbPerson3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtPersonId4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPersonId4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtPersonName4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPersonName4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''linkPerson4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkPerson4 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''linkEditPerson4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkEditPerson4 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''gbPerson4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbPerson4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtPersonId5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPersonId5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtPersonName5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPersonName5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''linkPerson5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkPerson5 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''linkEditPerson5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkEditPerson5 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''gbPerson5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbPerson5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtPersonId6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPersonId6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtPersonName6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPersonName6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''linkPerson6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkPerson6 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''linkEditPerson6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkEditPerson6 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''txtTotalPersonLoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalPersonLoan As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''gbPerson1_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbPerson1_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtTotalPersonLoan2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalPersonLoan2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''gbPerson2_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbPerson2_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtTotalPersonLoan3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalPersonLoan3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''gbPerson3_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbPerson3_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtTotalPersonLoan4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalPersonLoan4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''gbPerson4_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbPerson4_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtTotalPersonLoan5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalPersonLoan5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''gbPerson5_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbPerson5_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtTotalPersonLoan6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalPersonLoan6 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtSavingFound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSavingFound As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtRevenue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRevenue As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtOtherRevenue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherRevenue As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtCapitalMoney control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCapitalMoney As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtDebtAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDebtAmount As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtExpense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpense As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtFamilyExpense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFamilyExpense As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtExpenseDebt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpenseDebt As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtReqNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReqNote As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtBookAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBookAccount As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''ddlCollateral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCollateral As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtCollateralId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCollateralId As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtRealty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRealty As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtCreditLoanAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCreditLoanAmount As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''selCalInterest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selCalInterest As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''txtReqTotalAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReqTotalAmount As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtReqTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReqTerm As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtReqMonthTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReqMonthTerm As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtMonthFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMonthFinish As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''panelGroupCalculate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelGroupCalculate As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''dtCFLoanDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtCFLoanDate As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''dtCFDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtCFDate As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''dtSTCalDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtSTCalDate As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''updatepanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updatepanel3 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''dtSTPayDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtSTPayDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dtEndPayDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtEndPayDate As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''btnChangPayDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChangPayDate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtTotalCapital control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalCapital As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTerm As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''updatepanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updatepanel4 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''txtMinPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMinPayment As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtCalculateTypeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCalculateTypeName As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtCalculateType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCalculateType As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtInterestRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInterestRate As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''updatepanel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updatepanel5 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''txtTotalInterest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalInterest As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtFeeRate_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFeeRate_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTotalFeeAmount_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalFeeAmount_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtFeeRate_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFeeRate_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTotalFeeAmount_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalFeeAmount_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtFeeRate_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFeeRate_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTotalFeeAmount_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalFeeAmount_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtOverdueDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOverdueDay As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''txtOverdueRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOverdueRate As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnCalculate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCalculate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gvSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSchedule As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''gvLoanPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvLoanPay As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnPayLoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPayLoan As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCloseLoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseLoan As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtGTName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGTName1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtGTIdCard1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGTIdCard1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''gbGT2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbGT2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtGTName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGTName2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtGTIdCard2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGTIdCard2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''gbGT3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbGT3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtGTName3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGTName3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtGTIdCard3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGTIdCard3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''gbGT4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbGT4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtGTName4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGTName4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtGTIdCard4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGTIdCard4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''gbGT5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbGT5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtGTName5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGTName5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtGTIdCard5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGTIdCard5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTotalGTLoan1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalGTLoan1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''gbGT2_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbGT2_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtTotalGTLoan2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalGTLoan2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''gbGT3_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbGT3_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtTotalGTLoan3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalGTLoan3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''gbGT4_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbGT4_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtTotalGTLoan4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalGTLoan4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''gbGT5_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbGT5_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtTotalGTLoan5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalGTLoan5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''Text3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Text3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''RdOptPayCapital1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdOptPayCapital1 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RdOptPayCapital2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdOptPayCapital2 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''ddlAccNoPayCapital control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccNoPayCapital As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''RdOptRecieveMoney1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdOptRecieveMoney1 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RdOptRecieveMoney2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdOptRecieveMoney2 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RdOptRecieveMoney3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdOptRecieveMoney3 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txtAccBookNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccBookNo As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtAccountName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountName As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTypeAccId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTypeAccId As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTypeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTypeName As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''ckAutoPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckAutoPay As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CboBank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboBank As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTransToBankBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransToBankBranch As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTransToAccType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransToAccType As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTransToAccId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransToAccId As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTransToAccName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransToAccName As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''RdOptPayMoney1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdOptPayMoney1 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RdOptPayMoney2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdOptPayMoney2 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''ddlAccNoCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccNoCompany As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtBarcodeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBarcodeId As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''txtLoanFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLoanFee As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtDescription2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription2 As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''txtApproverId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApproverId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtAppoverName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAppoverName As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtApproverCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApproverCancel As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtApproverNameCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApproverNameCancel As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''DataList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DataList1 As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''AjaxFileUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AjaxFileUpload1 As Global.AjaxControlToolkit.AjaxFileUpload
    
    '''<summary>
    '''btnCapture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCapture As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgCapture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCapture As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ddlPrintRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPrintRequest As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''BtnPrintRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPrintRequest As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''ddlPrintAgreement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPrintAgreement As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnPrintAgreement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintAgreement As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''ddlPrintAttacth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPrintAttacth As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''BtnPrintAttacth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPrintAttacth As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''gbPrintGT1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbPrintGT1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlPrintGT1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPrintGT1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnPrintGT1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintGT1 As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''gbPrintGT2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbPrintGT2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlPrintGT2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPrintGT2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnPrintGT2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintGT2 As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''gbPrintGT3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbPrintGT3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlPrintGT3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPrintGT3 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnPrintGT3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintGT3 As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''gbPrintGT4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbPrintGT4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlPrintGT4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPrintGT4 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnPrintGT4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintGT4 As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''gbPrintGT5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbPrintGT5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlPrintGT5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPrintGT5 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnPrintGT5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintGT5 As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''ddlPrintCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPrintCard As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ckStPrintAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckStPrintAll As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''btnPrintCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintCard As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''dllPrintAllowPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dllPrintAllowPay As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnPrintAllowPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintAllowPay As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lblUserId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblEmpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpName As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''GVFollowTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVFollowTel As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''GVFollowHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVFollowHome As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnsave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button
End Class
