'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class personsub
    
    '''<summary>
    '''formperson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formperson As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''txtPersonId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPersonId As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtidcard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtidcard As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''cboTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTitle As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstName As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastName As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''dtBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtBirthDate As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAge As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''imgUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgUpload As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''AsyncFileUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AsyncFileUpload1 As Global.AjaxControlToolkit.AsyncFileUpload
    
    '''<summary>
    '''lblMesg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMesg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPicPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPicPath As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUpload As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''btnIdCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnIdCard As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtNationallity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNationallity As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''CboReligion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboReligion As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''txtCareer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCareer As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtBarcodeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBarcodeId As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''selsex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selsex As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''selMGStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selMGStatus As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''txtMarriageName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMarriageName As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtReferenceCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReferenceCode As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''GridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''BtnAddRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAddRow As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''txtBuiding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBuiding As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtAddr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddr As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtMoo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMoo As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtSoi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSoi As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtRoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRoad As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtLocality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocality As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDistrict As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProvince As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtZipCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtZipCode As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTel As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''TxtMobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtMobile As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtBuiding1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBuiding1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtAddr1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddr1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtmoo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmoo1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtsoi1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsoi1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtRoad1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRoad1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtLocality1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocality1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtDistrict1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDistrict1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtProvince1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProvince1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtZipCode1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtZipCode1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTel1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''TxtMobile1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtMobile1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtEmail1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtBuiding2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBuiding2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtAddr2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddr2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtmoo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmoo2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtsoi2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsoi2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtRoad2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRoad2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtLocality2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocality2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtDistrict2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDistrict2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtProvince2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProvince2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtZipCode2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtZipCode2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTel2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''TxtMobile2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtMobile2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtEmail2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''CboBank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboBank As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''txtBankBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBankBranch As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtBankAccType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBankAccType As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtBankAccNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBankAccNo As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtBankAccName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBankAccName As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompany As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtWorkPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWorkPosition As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtWorkDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWorkDepartment As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtWorkSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWorkSection As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''WorkStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WorkStartDate As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtWorkLife control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWorkLife As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtWorkSalary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWorkSalary As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''ckst2_loan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckst2_loan As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''ckst3_guaruntor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckst3_guaruntor As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''ckst1_deposit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckst1_deposit As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''ckst4_shared control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckst4_shared As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''ckst6_cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckst6_cancel As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''ckst5_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckst5_other As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''txtOtherStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherStatus As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''ckDisableLoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckDisableLoan As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''txtDisableLoanReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDisableLoanReason As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtCreditBureau control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCreditBureau As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''GridView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView2 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnsave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtIDCardID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDCardID As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtIDCardTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDCardTitle As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtIDCardFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDCardFirstName As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtIDCardLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDCardLastName As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtIDCardBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDCardBirthDate As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtIdCardSex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdCardSex As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtIDCardAddr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDCardAddr As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtIDCardMoo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDCardMoo As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtIDCardSoi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDCardSoi As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtIDCardRoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDCardRoad As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtIDCardLocality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDCardLocality As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtIDCardDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDCardDistrict As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtIDCardProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDCardProvince As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtIDCardPicture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDCardPicture As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''btnClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAddDataIDCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddDataIDCard As Global.System.Web.UI.WebControls.Button
End Class
