'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class settings

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''RdOptRound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdOptRound As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''rdOptRenew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdOptRenew As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''CKOptCloseLoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CKOptCloseLoan As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CkOptMinLoanPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CkOptMinLoanPay As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CkUseOpt3_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CkUseOpt3_1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtOpt3_1_Cond1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOpt3_1_Cond1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CkUseOpt3_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CkUseOpt3_2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtOpt3_2_Cond1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOpt3_2_Cond1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CkUseOpt3_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CkUseOpt3_3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtOpt3_3_Cond1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOpt3_3_Cond1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtOpt3_3_Cond2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOpt3_3_Cond2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CkUseOpt3_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CkUseOpt3_4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtOpt3_4_Cond1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOpt3_4_Cond1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtOpt3_4_Cond2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOpt3_4_Cond2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CkUseOpt3_5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CkUseOpt3_5 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtOpt3_5_Cond1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOpt3_5_Cond1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CkUseOpt3_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CkUseOpt3_6 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtOpt3_6_Cond1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOpt3_6_Cond1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CkUseOpt3_7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CkUseOpt3_7 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtOpt3_7_Cond1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOpt3_7_Cond1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CkUseOpt4_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CkUseOpt4_1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtOpt4_1_Cond1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOpt4_1_Cond1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CkUseOpt4_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CkUseOpt4_2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtOpt4_2_Cond1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOpt4_2_Cond1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtOpt4_2_Cond2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOpt4_2_Cond2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CkUseOpt4_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CkUseOpt4_3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnsave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button
End Class
