'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Site1
    
    '''<summary>
    '''head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents head As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''imgProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgProfile As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''UserName3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserName3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''imgProfile2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgProfile2 As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''lblusername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblusername As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblBranchName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBranchName As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblUserName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserName2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblBranchName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBranchName2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO1000 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO1000 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO1500 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO1500 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO1100 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO1100 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO1200 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO1200 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO1300 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO1300 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO1400 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO1400 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO2000 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO2000 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO2100 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO2100 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO2200 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO2200 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO2300 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO2300 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO3000 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO3000 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO3100 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO3100 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO3200 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO3200 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO3300 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO3300 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4000 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4000 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4100 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4100 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4110 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4110 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4120 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4120 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4130 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4130 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4140 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4140 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4150 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4150 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4160 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4160 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4170 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4170 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4180 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4180 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4200 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4200 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4210 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4210 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4220 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4220 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4230 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4230 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4240 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4240 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4250 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4250 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4260 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4260 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4300 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4300 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4310 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4310 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4320 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4320 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4330 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4330 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4340 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4340 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4350 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4350 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4360 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4360 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO4370 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO4370 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO5000 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO5000 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO5100 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO5100 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO5200 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO5200 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WLO9999 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WLO9999 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ContentPlaceHolder1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
