'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class typeloansub
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''txtTypeLoanId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTypeLoanId As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''ckStActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckStActive As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtTypeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTypeName As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtRefundName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRefundName As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRate As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtFeeRate_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFeeRate_1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtFeeRate_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFeeRate_2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtMaxRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaxRate As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtFeeRate_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFeeRate_3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''selFlagCollateral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selFlagCollateral As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''selFlagGuarantor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selFlagGuarantor As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''updatepanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updatepanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ddlBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBranch As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtIdFront control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdFront As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtIdRunning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdRunning As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''ckAutoRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckAutoRun As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ddlTypeLoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTypeLoan As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboMuclt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboMuclt As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''gbDeley control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gbDeley As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cboDeley control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeley As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''txtQtyTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtyTerm As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtLostOpportunity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLostOpportunity As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtDiscountIntRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiscountIntRate As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''ddlAccountCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccountCode As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAccountCode2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccountCode2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAccountCode3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccountCode3 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAccountCode4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccountCode4 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAccountCode6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccountCode6 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAccountCodeAccrued control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccountCodeAccrued As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAccountCode5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccountCode5 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAccountCodeFee1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccountCodeFee1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAccountCodeFee2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccountCodeFee2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAccountCodeFee3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccountCodeFee3 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAccountCode7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccountCode7 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''CboTypeGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboTypeGroup As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''CboTypeGroup2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboTypeGroup2 As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''btnsave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnsave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button
End Class
